bitbag_shipping_gateway:
    resource: |
        alias: bitbag.shipping_gateway
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show', 'index']
        redirect: update
        grid: bitbag_shipping_gateway
        vars:
            all:
                subheader: bitbag.shipping_export_plugin.shipping_gateways
                templates:
                    form: ShippingExportPlugin:ShippingGateway:_form.html.twig
            index:
                icon: cloud
    type: sylius.resource

bitbag_shipping_gateway_index:
    path: /products/
    methods: [GET]
    defaults:
        _controller: bitbag.shipping_export_plugin.controller.product:indexAction
        _sylius:
            section: admin
            grid: bitbag_shipping_gateway
            template: ShippingExportPlugin:ShippingGateway:index.html.twig
            vars:
                subheader: bitbag.shipping_export_plugin.manage_shipping_gateways
                icon: cube

bitbag_shipping_gateway_per_taxon_index:
    path: /products/taxon/{taxonId}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            section: admin
            grid: bitbag_shipping_gateway_from_taxon
            template: ShippingExportPlugin:ShippingGateway:index.html.twig
            vars:
                subheader: bitbag.shipping_export_plugin.manage_shipping_gateway
                icon: cube

bitbag_shipping_gateway_create:
    path: /products/new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            section: admin
            template: SyliusAdminBundle:Crud:create.html.twig
            redirect: bitbag_shipping_gateway_update
            vars:
                subheader: bitbag.shipping_export_plugin.create_shipping_gateway
                templates:
                    form: ShippingExportPlugin:ShippingGateway:_form.html.twig
                route:
                    name: bitbag_shipping_gateway_create
