bitbag_admin_shipping_gateway:
    resource: |
        alias: bitbag.shipping_gateway
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: bitbag_admin_shipping_gateway
        permission: true
        vars:
            all:
                subheader: bitbag.ui.manage_shipping_gateways_available_to_your_customers
                templates:
                    form: ShippingGatewayPlugin:ShippingGateway:_form.html.twig
            index:
                icon: payment
    type: sylius.resource

bitbag_admin_shipping_gateway_create:
    path: /shipping-gateways/new/{factory}
    methods: [GET, POST]
    defaults:
        _controller: bitbag.controller.shipping_gateway:createAction
        _sylius:
            section: admin
            template: SyliusAdminBundle:Crud:create.html.twig
            redirect: bitbag_admin_shipping_gateway_update
            permission: true
            vars:
                subheader: bitbag.ui.manage_shipping_gateways_available_to_your_customers
                templates:
                    form: ShippingGatewayPlugin:ShippingGateway:_form.html.twig
                route:
                    parameters:
                        factory: $factory

bitbag_admin_get_shipping_gateways:
    path: /shipping-gateways/list
    methods: [GET]
    defaults:
        _controller: bitbag.controller.shipping_gateway:getShippingGatewaysAction
        template: ShippingExportPlugin:ShippingGateway/Gateways:shippingGateways.html.twig
