sylius_grid:
    grids:
        bitbag_admin_shipping_gateway:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag.model.shipping_gateway.class%"
                    repository:
                        method: createListQueryBuilder
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: code
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, shippingMethod.translation.name, status]
            actions:
                main:
                    create:
                        type: links
                        label: sylius.ui.create
                        options:
                            class: primary
                            icon: "tabler:plus"
                            header:
                                icon: "tabler:cube"
                                label: sylius.ui.type
                            links:
                item:
                    update:
                        type: update
                    delete:
                        type: delete

