sylius_grid:
    templates:
        action:
            export_shipments: "@BitBagSyliusShippingExportPlugin/ShippingExport/Action/_exportShipments.html.twig"
    grids:
        bitbag_admin_shipping_export:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag.model.shipping_export.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                shipment: desc
            fields:
                order:
                    type: twig
                    label: sylius.ui.order
                    path: .
                    sortable: shipment.order
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/orderNumber.html.twig"
                shipment:
                    type: datetime
                    label: sylius.ui.created_at
                    path: shipment.createdAt
                    sortable: shipment.createdAt
                    options:
                        format: 'd-m-Y H:i:s'
                exportedAt:
                    type: twig
                    label: bitbag.ui.exported_at
                    path: .
                    sortable: ~
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/exportedAt.html.twig"
                shippingMethod:
                    type: twig
                    label: sylius.ui.shipping_method
                    path: .
                    sortable: ~
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/shippingMethod.html.twig"
                labelPath:
                    type: twig
                    label: bitbag.ui.shipping_export_label
                    path: .
                    sortable: ~
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/shippingExportLabel.html.twig"
                state:
                    type: twig
                    label: sylius.ui.state
                    path: .
                    sortable: ~
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/state.html.twig"
            filters:
                order:
                    type: string
                    label: sylius.ui.order
                    form_options:
                        type: contains
                    options:
                        fields: [shipment.order.number]
                state:
                    type: select
                    label: sylius.ui.state
                    form_options:
                        choices:
                            bitbag.ui.new: New
                            bitbag.ui.pending: Pending
                            bitbag.ui.exported: Exported
                shippingMethod:
                    type: entity
                    label: sylius.ui.shipping_method
                    form_options:
                        class: "%sylius.model.shipping_method.class%"
                    options:
                        field: shipment.method
                createdAt:
                    type: date
                    label: sylius.ui.created_at
                    options:
                        field: shipment.createdAt
                exportedAt:
                    type: date
                    label: bitbag.ui.exported_at
            actions:
                main:
                    create:
                        type: export_shipments
