sylius_grid:
    grids:
        bitbag_admin_shipping_gateway:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag.model.shipping_gateway.class%"
                    repository:
                        method: createListQueryBuilder
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                label:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, translation.name]
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create_shipping_gateway
                item:
                    update:
                        type: update
                    delete:
                        type: delete
