sylius_resoruce:
    shipping_gateway:
        product:
            classes:
                model: BitBag\ShippingExportPlugin\Entity\ShippingGateway
#                form: BitBag\ShippingExportPlugin\Form\Type\ShippingGatewayType
            translation:
                classes:
                    model: BitBag\ShippingExportPlugin\Entity\ShippingGatewayTranslation
