sylius_resource:
    resources:
        bitbag.shipping_gateway:
            classes:
                model: BitBag\ShippingExportPlugin\Entity\ShippingGateway
                repository:  BitBag\ShippingExportPlugin\Repository\ShippingGatewayRepository
                form: BitBag\ShippingExportPlugin\Form\Type\ShippingGatewayType
                controller: BitBag\ShippingExportPlugin\Controller\ShippingGatewayController
            translation:
                classes:
                    model: BitBag\ShippingExportPlugin\Entity\ShippingGatewayTranslation