sylius_resource:
    resources:
        bitbag.shipping_export:
            classes:
                model: BitBag\ShippingExportPlugin\Entity\ShippingExport
                repository:  BitBag\ShippingExportPlugin\Repository\ShippingExportRepository
                form: BitBag\ShippingExportPlugin\Form\Type\ShippingGatewayType
                controller: BitBag\ShippingExportPlugin\Controller\ShippingExportController