imports:
    - { resource: "resource/**/*.yml" }
    - { resource: "grids/**/*.yml" }
    - { resource: "services.yml" }

sylius_grid:
    templates:
        action:
            create_shipping_gateway: "@BitBagSyliusShippingExportPlugin/ShippingGateway/Action/_create.html.twig"
            export_shipments: "@BitBagSyliusShippingExportPlugin/ShippingExport/Action/_exportShipments.html.twig"
