imports:
    - { resource: "@ShippingExportPlugin/Resources/config/resource/bitbag_shipping_gateway.yml" }
    - { resource: "@ShippingExportPlugin/Resources/config/grids/shipping_gateway.yml" }
    - { resource: "@ShippingExportPlugin/Resources/config/services.yml" }

sylius_grid:
    templates:
        action:
            create_shipping_gateway: "@ShippingExportPlugin/ShippingGateway/Action/create.html.twig"
