imports:
    - { resource: "@BitBagSyliusShippingExportPlugin/Resources/config/resource/bitbag_shipping_gateway.yml" }
    - { resource: "@BitBagSyliusShippingExportPlugin/Resources/config/resource/bitbag_shipping_export.yml" }
    - { resource: "@BitBagSyliusShippingExportPlugin/Resources/config/grids/bitbag_shipping_gateway.yml" }
    - { resource: "@BitBagSyliusShippingExportPlugin/Resources/config/grids/bitbag_shipping_export.yml" }
    - { resource: "@BitBagSyliusShippingExportPlugin/Resources/config/services.yml" }

sylius_grid:
    templates:
        action:
            create_shipping_gateway: "@BitBagSyliusShippingExportPlugin/ShippingGateway/Action/_create.html.twig"
            export_shipments: "@BitBagSyliusShippingExportPlugin/ShippingExport/Action/_exportShipments.html.twig"
