bitbag_shipping_gateway:
    resource: "@BitBagShippingExportPlugin/Resources/config/routing/bitbag_shipping_gateway.yml"

bitbag_shipping_export:
    resource: "@BitBagShippingExportPlugin/Resources/config/routing/bitbag_shipping_export.yml"
