parameters:
    bitbag.shipping_gateway.validation_groups: ['bitbag']

services:
    bitbag.shipping_export_plugin.listener.admin.menu_builder:
        class: BitBag\ShippingExportPlugin\Menu\ShippingGatewayMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

    bitbag.shipping_export_plugin.shipping_gateway.form.type:
        class: BitBag\ShippingExportPlugin\Form\Type\ShippingGatewayType
        arguments:
            - '%bitbag.model.shipping_gateway.class%'
            - '%bitbag.shipping_gateway.validation_groups%'
            - '@bitbag.shipping_export_plugin.context.shipping_gateway_type'
            - '@sylius.repository.shipping_method'
            - '%sylius.model.shipping_method.class%'
        tags:
            - { name: form.type }

    bitbag.form_registry.shipping_gateway_config:
        class: Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

    bitbag.shipping_export_plugin.context.shipping_gateway_type:
        class: BitBag\ShippingExportPlugin\Context\ShippingGatewayContext
        arguments:
            - "@request_stack"
            - "@bitbag.form_registry.shipping_gateway_config"
            - "@bitbag.repository.shipping_gateway"
            - "%bitbag.shipping_gateways%"