BitBag\ShippingExportPlugin\Entity\ShippingGatewayTranslation:
    type: entity
    table: bitbag_shipping_gateway_translation
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            column: name