BitBag\SyliusShippingExportPlugin\Entity\ShippingGateway:
    type: mappedSuperclass
    table: bitbag_shipping_gateway
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        code:
            type: string
            column: code

        config:
            type: json_array
            column: config

        name:
            type: string
            column: name
    manyToMany:
        shippingMethods:
            targetEntity: Sylius\Component\Core\Model\ShippingMethod
            joinTable:
                name: bitbag_shipping_gateway_method
                joinColumns:
                    shipping_gateway_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    shipping_method_id:
                        referencedColumnName: id
    oneToMany:
        shippingExports:
            targetEntity: BitBag\SyliusShippingExportPlugin\Entity\ShippingExportInterface
            mappedBy: shippingGateway
            orphanRemoval: true
