BitBag\SyliusShippingExportPlugin\Entity\ShippingGateway:
    type: entity
    table: bitbag_shipping_gateway
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        code:
            type: string
            column: code

        config:
            type: json_array
            column: config

        label:
            type: string
            column: name

    manyToOne:
        shippingMethod:
            targetEntity: Sylius\Component\Core\Model\ShippingMethod
            joinColumn:
                name: shipping_method_id
                referencedColumnName: id
    oneToMany:
        shippingExports:
            targetEntity: BitBag\SyliusShippingExportPlugin\Entity\ShippingExport
            mappedBy: shippingGateway
            orphanRemoval: true