BitBag\ShippingExportPlugin\Entity\ShippingExport:
    type: entity
    table: bitbag_shipping_export
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        exportedAt:
            type: datetime
            column: exported_at
            nullable: true
        labelPath:
            type: string
            column: label_path
            nullable: true
        state:
            type: string
            column: state
    oneToOne:
        shipment:
            targetEntity: Sylius\Component\Core\Model\Shipment
            joinColumn:
                name: shipment_id
                referencedColumnName: id
            cascade: ['persist']
    manyToOne:
        shippingGateway:
            targetEntity: BitBag\ShippingExportPlugin\Entity\ShippingGateway
            joinColumn:
                name: shipping_gateway_id
                referencedColumnName: id