BitBag\SyliusShippingExportPlugin\Entity\ShippingExport:
    type: mappedSuperclass
    table: bitbag_shipping_export
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        exportedAt:
            type: datetime
            column: exported_at
            nullable: true
        labelPath:
            type: string
            column: label_path
            nullable: true
        state:
            type: string
            column: state
        externalId:
            type: string
            column: external_id
            nullable: true
    oneToOne:
        shipment:
            targetEntity: Sylius\Component\Shipping\Model\ShipmentInterface
            joinColumn:
                name: shipment_id
                referencedColumnName: id
            cascade: ['ALL']
    manyToOne:
        shippingGateway:
            targetEntity: BitBag\SyliusShippingExportPlugin\Entity\ShippingGatewayInterface
            inversedBy: shippingExports
            joinColumn:
                name: shipping_gateway_id
                referencedColumnName: id
            cascade: ['ALL']
